description "Docker Registry"
version "0.9.1"
author "Docker, Inc."

start on runlevel [2345]
stop on runlevel [016]

respawn
respawn limit 10 5

script
  cd $REGISTRY_HOME
  exec gunicorn -k gevent --max-requests 100 -e SETTINGS_FLAVOR=prod \
    --graceful-timeout 3600 -t 3600 -b localhost:5000 -w 8 \
    --access-logfile /var/log/docker-registry/access.log \
    --error-logfile /var/log/docker-registry/server.log \
    docker_registry.wsgi:application
end script